# Generated by Django 4.2 on 2023-05-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0002_alter_candidate_point_alter_candidate_test_attempted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='point',
            new_name='points',
        ),
    ]
